import { Planet } from './types';

export const celestials: Planet[] = [
  {
    id: 'sun',
    name: 'Sun',
    nameIndo: 'Matahari',
    color: '#f97316',
    borderColor: '#ea580c',
    glowColor: 'rgba(249, 115, 22, 0.6)',
    radius: 28,
    distance: 0,
    realRadius: '696,340 km',
    realDistance: '0 km (Pusat Tata Surya)',
    realTemp: '5,500°C (Permukaan) / 15 Juta°C (Inti)',
    rotation: '25-35 hari',
    revolution: '230 Juta tahun (Mengitari Galaksi)',
    gravity: '274 m/s² (28x Bumi)',
    mass: '333,000x Bumi',
    moons: 0,
    moonsList: [],
    type: 'star',
    funFact: 'Matahari menyumbang 99.86% dari seluruh massa di sistem tata surya kita.',
    deskripsi: 'Matahari adalah bintang di pusat Tata Surya yang berupa bola plasma panas membara. Energi radiasinya menyokong seluruh kehidupan di Bumi melalui fotosintesis dan mengendalikan iklim serta cuaca global.',
    structure: {
      core: 'Inti (Core): Zona fusi nuklir dengan suhu 15 juta °C tempat hidrogen bergabung menjadi helium dan melepaskan energi luar biasa.',
      mantle: 'Zona Radiatif & Konvektif: Lapisan tempat energi bergerak keluar melalui radiasi foton (memakan waktu ribuan tahun) lalu mengalir secara konvektif seperti air mendidih.',
      crust: 'Fotosfer (Photosphere): "Permukaan" tampak Matahari yang mengeluarkan cahaya kuning hangat dengan suhu sekitar 5,500 °C.',
      atmosphere: 'Korona (Corona): Atmosfer terluar Matahari yang sangat tipis namun bersuhu ekstrem mencapai jutaan derajat Celsius, terlihat saat gerhana matahari total.'
    }
  },
  {
    id: 'mercury',
    name: 'Mercury',
    nameIndo: 'Merkurius',
    color: '#94a3b8',
    borderColor: '#64748b',
    glowColor: 'rgba(148, 163, 184, 0.4)',
    radius: 8,
    distance: 45,
    realRadius: '2,439 km',
    realDistance: '57.9 Juta km',
    realTemp: '-180°C hingga 430°C',
    rotation: '59 hari',
    revolution: '88 hari',
    gravity: '3.7 m/s²',
    mass: '0.055x Bumi',
    moons: 0,
    moonsList: [],
    type: 'terrestrial',
    funFact: 'Satu tahun di Merkurius hanya berlangsung 88 hari Bumi, namun satu harinya setara dengan 176 hari Bumi!',
    deskripsi: 'Merkurius adalah planet terkecil di Tata Surya dan yang paling dekat dengan Matahari. Karena hampir tidak memiliki atmosfer untuk menahan panas, planet ini mengalami perbedaan suhu paling ekstrem antara siang dan malam.',
    structure: {
      core: 'Inti Besi Raksasa: Merkurius memiliki inti besi cair yang luar biasa besar, mencakup sekitar 85% dari total radius planet.',
      mantle: 'Mantel Silikat Pembatas: Lapisan mantel berbatu tebal sekitar 300-400 km di atas inti besinya.',
      crust: 'Kerak Silikat Berlubang: Kerak berbatu abu-abu gelap penuh kawah akibat tumbukan asteroid karena tidak ada atmosfer pelindung.',
      atmosphere: 'Eksosfer Tipis: Hanya atmosfer sementara yang terdiri dari atom hidrogen, helium, dan oksigen yang tertiup angin matahari.'
    }
  },
  {
    id: 'venus',
    name: 'Venus',
    nameIndo: 'Venus',
    color: '#fbbf24',
    borderColor: '#d97706',
    glowColor: 'rgba(251, 191, 36, 0.4)',
    radius: 12,
    distance: 70,
    realRadius: '6,051 km',
    realDistance: '108.2 Juta km',
    realTemp: '465°C',
    rotation: '243 hari (Arah Terbalik/Retrograde)',
    revolution: '225 hari',
    gravity: '8.87 m/s²',
    mass: '0.815x Bumi',
    moons: 0,
    moonsList: [],
    type: 'terrestrial',
    funFact: 'Venus berputar berlawanan arah dari kebanyakan planet (Matahari terbit dari barat) dan berotasi lebih lambat dibanding waktu revolusinya.',
    deskripsi: 'Venus sering disebut sebagai planet kembaran Bumi karena ukurannya yang mirip. Namun, Venus adalah planet terpanas di Tata Surya akibat efek rumah kaca ekstrem yang disebabkan oleh atmosfer tebal karbon dioksida basah awan asam sulfat.',
    structure: {
      core: 'Inti Besi-Nikel Semi-Cair: Diperkirakan berdiameter sekitar 6,000 km mirip dengan ukuran inti Bumi namun medan magnetnya sangat lemah.',
      mantle: 'Mantel Batuan Silikat: Mantel berbatu setebal sekitar 3,000 km yang menyusun sebagian besar volume planet.',
      crust: 'Kerak Basaltik Volkanik: Lapisan luar setebal 10-30 km yang didominasi daratan lava membeku dan ribuan gunung berapi aktif.',
      atmosphere: 'Atmosfer Super-Tebal CO₂: Atmosfer yang sangat padat dengan tekanan 92 kali lipat Bumi, diselimuti awan asam sulfat beracun pemantul cahaya.'
    }
  },
  {
    id: 'earth',
    name: 'Earth',
    nameIndo: 'Bumi',
    color: '#3b82f6',
    borderColor: '#1d4ed8',
    glowColor: 'rgba(59, 130, 246, 0.5)',
    radius: 13,
    distance: 100,
    realRadius: '6,371 km',
    realDistance: '149.6 Juta km',
    realTemp: '15°C (Rata-rata)',
    rotation: '24 jam',
    revolution: '365.25 hari',
    gravity: '9.81 m/s²',
    mass: '1.0x Bumi (5.97 x 10^24 kg)',
    moons: 1,
    moonsList: ['Bulan (Luna)'],
    type: 'terrestrial',
    funFact: 'Bumi adalah satu-satunya tempat yang diketahui mendukung kehidupan dan memiliki air cair yang melimpah di permukaannya.',
    deskripsi: 'Bumi adalah planet ketiga dari Matahari, tempat tinggal kita. Bumi unik karena memiliki biosfer aktif, lempeng tektonik, medan magnet kuat pelindung radiasi, serta siklus air dinamis yang menyeimbangkan suhu kehidupan.',
    structure: {
      core: 'Inti Dalam Padat & Luar Cair: Inti dalam terbuat dari besi-nikel padat bersuhu mirip permukaan Matahari, dikelilingi inti luar cair penyusun medan magnet bumi.',
      mantle: 'Mantel Silikat Berplastis: Lapisan silikat kental tebal 2,900 km tempat arus konveksi menggerakkan lempeng tektonik kerak di atasnya.',
      crust: 'Kerak Tektonik Tipis: Lapisan luar berbatu (5-70 km) yang terbagi atas kerak benua ringan dan kerak samudra basah yang padat.',
      atmosphere: 'Atmosfer Nitrogen-Oksigen: Kaya nitrogen (78%) dan oksigen (21%) yang menyokong respirasi makhluk hidup serta menyaring sinar ultraviolet.'
    }
  },
  {
    id: 'mars',
    name: 'Mars',
    nameIndo: 'Mars',
    color: '#ef4444',
    borderColor: '#b91c1c',
    glowColor: 'rgba(239, 68, 68, 0.4)',
    radius: 10,
    distance: 130,
    realRadius: '3,389 km',
    realDistance: '227.9 Juta km',
    realTemp: '-62°C',
    rotation: '24.6 jam',
    revolution: '687 hari',
    gravity: '3.71 m/s²',
    mass: '0.107x Bumi',
    moons: 2,
    moonsList: ['Phobos', 'Deimos'],
    type: 'terrestrial',
    funFact: 'Mars memiliki gunung berapi terbesar di Tata Surya bernama Olympus Mons, tingginya tiga kali gunung Everest!',
    deskripsi: 'Mars dijuluki "Planet Merah" karena kandungan besi oksida (karat) di permukaannya. Mars adalah planet gurun dingin yang memiliki sisa-sisa aliran air kuno dan merupakan target utama manusia dalam penjelajahan antarplanet.',
    structure: {
      core: 'Inti Besi-Nikel-Sulfur Padat: Inti kecil pasif berdiameter sekitar 1,500-2,000 km menyerupai kapsul logam kuno.',
      mantle: 'Mantel Batuan Statis: Mantel setebal 1,600 km yang kaku dan tidak mengalirkan lempeng tektonik aktif seperti Bumi.',
      crust: 'Kerak Besi Oksida Tebal: Lapisan kaya zat besi berdebu tebal 50-100 km, tergores ngarai terdalam Valles Marineris.',
      atmosphere: 'Atmosfer Karbon Dioksida Tipis: Sangat tipis (hanya 1% kepadatan Bumi) didominasi CO₂ membawa badai debu global sesekali.'
    }
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    nameIndo: 'Yupiter',
    color: '#f59e0b',
    borderColor: '#b45309',
    glowColor: 'rgba(245, 158, 11, 0.4)',
    radius: 22,
    distance: 170,
    realRadius: '69,911 km',
    realDistance: '778.5 Juta km',
    realTemp: '-108°C',
    rotation: '9.9 jam (Tercepat di Tata Surya)',
    revolution: '11.8 tahun',
    gravity: '24.79 m/s² (2.5x Bumi)',
    mass: '318x Bumi',
    moons: 95,
    moonsList: ['Ganymede', 'Callisto', 'Io', 'Europa'],
    type: 'gas_giant',
    funFact: 'Badai elips raksasa "Great Red Spot" di Yupiter telah mengamuk selama setidaknya 300 tahun dan ukurannya lebih besar dari Bumi!',
    deskripsi: 'Yupiter adalah planet terbesar di Tata Surya. Sebagai raksasa gas, Yupiter didominasi oleh hidrogen dan helium tanpa permukaan padat yang jelas, dikelilingi puluhan satelit eksotis termasuk Europa yang diduga menyimpan samudera bawah es.',
    structure: {
      core: 'Inti Batuan Logam Padat: Diperkirakan berupa bola campuran batu, es, dan logam hidrogen yang tertekan sangat dahsyat.',
      mantle: 'Hidrogen Metalik Cair Semacam Logam: Lautan hidrogen yang begitu tertekan ekstrem hingga berperilaku seperti logam cair penghasil magnetosfer super kuat.',
      crust: 'Samudra Hidrogen Molekuler Cair: Lapisan tanpa batas jelas yang bertransisi dari gas tebal atmosfer menjadi cairan hidrogen murni.',
      atmosphere: 'Pita Awan Amonia & Metana: Lapisan atmosfer atas berwarna-warni yang berputar dengan kecepatan tinggi menghasilkan badai siklon raksasa.'
    }
  },
  {
    id: 'saturn',
    name: 'Saturn',
    nameIndo: 'Saturnus',
    color: '#fef08a',
    borderColor: '#ca8a04',
    glowColor: 'rgba(254, 240, 138, 0.4)',
    radius: 19,
    distance: 215,
    realRadius: '58,232 km',
    realDistance: '1.43 Milyar km',
    realTemp: '-139°C',
    rotation: '10.7 jam',
    revolution: '29.5 tahun',
    gravity: '10.44 m/s²',
    mass: '95x Bumi',
    moons: 146,
    moonsList: ['Titan', 'Rhea', 'Enceladus', 'Mimas'],
    type: 'gas_giant',
    funFact: 'Kincir cincin cantik Saturnus terbuat dari miliaran serpihan es, debu, dan puing batu seukuran pasir hingga gunung kecil.',
    deskripsi: 'Saturnus terkenal dengan sistem cincinnya yang megah dan sangat spektakuler. Saturnus adalah planet dengan massa jenis terendah di Tata Surya, bahkan jika ada kolam air yang sangat besar, planet ini akan mengapung di atasnya!',
    structure: {
      core: 'Inti Batuan Silikat-Besi: Bola inti padat bersuhu tinggi berukuran sekitar 9 hingga 22 kali massa Bumi.',
      mantle: 'Hidrogen Metalik Cair Cairan Logam: Lapisan konvektif hidrogen bertekanan tinggi mirip Yupiter namun dengan kandungan helum mengendap ke bawah.',
      crust: 'Zona Hidrogen Molekuler Cair: Zona transisi tebal di mana gas atmosfer mendingin menjadi bentuk cair tanpa batas daratan padat.',
      atmosphere: 'Atmosfer Kabut Nitrogen-Metana: Atmosfer gas hidrogen-helium kekuningan karena kristal amonia, dihiasi badai heksagonal spektakuler di kutub utaranya.'
    }
  },
  {
    id: 'uranus',
    name: 'Uranus',
    nameIndo: 'Uranus',
    color: '#a5f3fc',
    borderColor: '#0891b2',
    glowColor: 'rgba(165, 243, 252, 0.4)',
    radius: 15,
    distance: 260,
    realRadius: '25,362 km',
    realDistance: '2.87 Milyar km',
    realTemp: '-224°C',
    rotation: '17.2 jam (Sumbu miring 98°)',
    revolution: '84 tahun',
    gravity: '8.69 m/s²',
    mass: '14.5x Bumi',
    moons: 28,
    moonsList: ['Titania', 'Oberon', 'Umbriel', 'Ariel'],
    type: 'ice_giant',
    funFact: 'Uranus berputar miring hampir 98 derajat pada sumbunya, tampak seperti bola yang menggelinding mengitari Matahari!',
    deskripsi: 'Uranus adalah raksasa es berwarna biru kehijauan pucat karena kandungan metana di atmosfernya. Planet ini memiliki atmosfer terdingin di Tata Surya serta dipenuhi angin kencang tak henti-hentinya.',
    structure: {
      core: 'Inti Batuan Silikat-Besi Kecil: Berdiameter kecil dengan tekanan rendah dibandingkan planet raksasa lainnya.',
      mantle: 'Samudra Es Air, Amonia & Metana Gletser: Struktur mantel berupa cairan "mantel es" kental berwarna biru pekat kaya amonia panas berair.',
      crust: 'Selubung Hidrogen-Helium Cair: Lapisan tebal gas terkompresi yang menyatu dengan bagian atas mantel es.',
      atmosphere: 'Atmosfer Kaya Metana Hijau Pucat: Dipenuhi gas hidrogen, helium, dan metana di puncak yang menyerap warna merah matahari dan memantulkan biru.'
    }
  },
  {
    id: 'neptune',
    name: 'Neptune',
    nameIndo: 'Neptunus',
    color: '#60a5fa',
    borderColor: '#2563eb',
    glowColor: 'rgba(96, 165, 252, 0.4)',
    radius: 14,
    distance: 300,
    realRadius: '24,622 km',
    realDistance: '4.5 Milyar km',
    realTemp: '-201°C',
    rotation: '16.1 jam',
    revolution: '164.8 tahun',
    gravity: '11.15 m/s²',
    mass: '17x Bumi',
    moons: 16,
    moonsList: ['Triton', 'Proteus', 'Nereid'],
    type: 'ice_giant',
    funFact: 'Neptunus adalah planet terjauh dari Matahari dan memiliki kecepatan angin tercepat di Tata Surya, meluncur hingga 2,100 km/jam!',
    deskripsi: 'Neptunus adalah raksasa es biru tua yang gelap, dingin, dan berangin kencang ekstrem. Penemuannya diprediksi secara matematis sebelum teleskop mengonfirmasinya secara visual pada tahun 1846.',
    structure: {
      core: 'Inti Batuan Logam Padat: Inti batu-besi bermassa sekitar 1.2 kali massa Bumi di pusat ekstrim planet.',
      mantle: 'Mantel Air-Amonia-Metane Super Padat: Samudra mantel cairan superkritis penghantar listrik tinggi tempat terjadinya hujan "intan" kristal berlian.',
      crust: 'Transisi Cair-Gas Hidrogen: Campuran gas hidrokarbon kompresi yang mengelilingi planet secara terus-menerus.',
      atmosphere: 'Atmosfer Biru Kobalt Metana Pekat: Atmosfer hidrogen-helium berhiaskan pita awan metana putih melayang di atas "Great Dark Spot".'
    }
  },
  {
    id: 'pluto',
    name: 'Pluto',
    nameIndo: 'Pluto',
    color: '#cbd5e1',
    borderColor: '#94a3b8',
    glowColor: 'rgba(203, 213, 225, 0.3)',
    radius: 6,
    distance: 330,
    realRadius: '1,188 km',
    realDistance: '5.9 Milyar km',
    realTemp: '-229°C',
    rotation: '153 jam (6.4 hari)',
    revolution: '248 tahun',
    gravity: '0.62 m/s²',
    mass: '0.0022x Bumi',
    moons: 5,
    moonsList: ['Charon', 'Nix', 'Hydra', 'Kerberos', 'Styx'],
    type: 'dwarf',
    funFact: 'Pluto memiliki bentang dataran es nitrogen berbentuk hati raksasa di permukaannya bernama Tombaugh Regio.',
    deskripsi: 'Pluto diklasifikasikan sebagai planet kerdil sejak tahun 2006. Planet es kecil di Sabuk Kuiper ini memiliki orbit yang sangat lonjong dan miring, serta berpasangan dengan Charon seperti planet biner karena gravitasi bersama.',
    structure: {
      core: 'Inti Batuan Silikat Besar: Menyusun sekitar 70% dari struktur interior Pluto mendingin berlapis sisa panas radioaktif kuno.',
      mantle: 'Mantel Es Air Tebal Berair: Mantel es menyelimuti inti dengan kemungkinan lumeran laut cair sangat tipis di bawah kerak es.',
      crust: 'Kerak Es Nitrogen, Metana & Air Padat: Permukaan es berwarna-warni kontras tinggi yang meluas berkerut es karbondioksida.',
      atmosphere: 'Atmosfer Nitrogen Tipis Mengembang: Atmosfer musiman yang mengembang menjadi gas tipis saat Pluto mendekati matahari dan runtuh membeku saat menjauh.'
    }
  }
];
